### ISSUE TITLE
Tracking: AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by wayalan** [MIC-DKFZ/TractSeg#122]
Dear TractSeger

I have installed the TractSeg from the master and tried to test the routine commands for installation testing.
I tried to follow the scripts here:

TractSeg -i Diffusion.nii.gz -o tractseg_output --output_type tract_segmentation --raw_diffusion_input --preprocess
OK
TractSeg -i tractseg_output/peaks.nii.gz -o tractseg_output --output_type endings_segmentation --preprocess
OK
TractSeg -i tractseg_output/peaks.nii.gz -o tractseg_output --output_type TOM --preprocess
OK

Tracking -i tractseg_output/peaks.nii.gz -o tractseg_output
Failed

I keep getting this error message: AttributeError: module '__main__' has no attribute '__spec__'
Can someone tell me how to solve it? or how can I generate tracts by using MRTrix?

I am using MacOS Catalina, python 3.8

Best Regards,
Alan

**Comment by ConorOW** [comment]
Hey Alan,
I am having a similar issue! I can get peaks, tract segmentation, endpoint segmentation and TOM all to work, but cannot perform the tracking bit. Have you managed to find a work around?

**Comment by wayalan** [comment]
Hi ConorOW

I still have problems with Tracking function with my installation,  but I managed to perform that function using docker, however, it is awkward because my dockers have problems with tract/endpoint segmentation...so I have to switch between them...

Still looking for solutions, please let me know if you or anyone figure out how to solve this problem in macos.

> Hey Alan,
> I am having a similar issue! I can get peaks, tract segmentation, endpoint segmentation and TOM all to work, but cannot perform the tracking bit. Have you managed to find a work around?

**Comment by wasserth** [comment]
Sorry for the late reply. I was on vacation. 
The problem might be python 3.8. I only tested with python <=3.7. Can you try if it works with 3.7 or 3.5?
MacOS should be fine.
Could you also post the complete error message (showing the code file and the line of code where the error occurs)?
