### ISSUE TITLE
Dipy dependence failure

### ISSUE THREAD

**Issue by kerkelae** [MIC-DKFZ/TractSeg#47]
Following the instructions (https://github.com/MIC-DKFZ/TractSeg/#install), I installed TractSeg and tried to run it, but could not because the current version of DiPy does not have the move_streamlines() function in dipy.tracking.utils. I tried to fix this by creating a new virtual environment without DiPy, but the installation of TractSect failed to download the required function from DiPy. This function is something that has been removed from the most recent release of DiPy. See below the error message I got after calling 'TractSeg' after installation. 

Traceback (most recent call last):
  File "/home/leevi/anaconda3/envs/tractseg/bin/TractSeg", line 38, in <module>
    from tractseg.libs import mrtrix
  File "/home/leevi/anaconda3/envs/tractseg/lib/python3.7/site-packages/tractseg/libs/mrtrix.py", line 29, in <module>
    from tractseg.libs import tracking
  File "/home/leevi/anaconda3/envs/tractseg/lib/python3.7/site-packages/tractseg/libs/tracking.py", line 9, in <module>
    from dipy.tracking.utils import move_streamlines
ImportError: cannot import name 'move_streamlines' from 'dipy.tracking.utils' (/home/leevi/anaconda3/envs/tractseg/lib/python3.7/site-packages/dipy/tracking/utils.py)

Is there something that I am missing?

**Comment by drs-m** [comment]
I have the same problem

**Comment by meconomou** [comment]
Had the same problem. Thanks for the tip!

**Comment by wasserth** [comment]
The newest `master` of TractSeg works with dipy 1.0. If you are using an older version of TractSeg you willl have to manually install dipy 0.15 or 0.16.
