### ISSUE TITLE
Error: Can't plot tractometry results

### ISSUE THREAD

**Issue by LucSam** [MIC-DKFZ/TractSeg#21]
Hi,

we received following error when trying to plot the tractometry results:

```
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
AttributeError: 'module' object has no attribute 'lineplot'
```

We changed `plt.tight_layout()` to  `plt.show()` and installed seaborn 0.9.0 via `pip install seaborn==0.9.0`, which solved the problem.

**Comment by wasserth** [comment]
Thanks for the hint. It does not work with seaborn < 0.9. I should mention that somewhere. But with seaborn 0.9.0 plt.tight_layout() works for me.

**Comment by wasserth** [comment]
I added more comments to the code to make people aware of those issues.
